# Generated by Django 5.0.6 on 2026-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_farmer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='farmer',
            name='gmail',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='allowances',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=10),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='snf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
