# Generated by Django 5.0.6 on 2026-05-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_remove_farmer_created_at_farmer_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkcollection',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='session',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='snf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='milkcollection',
            unique_together={('farmer', 'date', 'session')},
        ),
    ]
