# Generated by Django 5.0.6 on 2026-05-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0008_noticeread'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
